/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type FaqBlock = {
  _type: 'faqBlock';
  title?: string;
  faqs?: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    _key: string;
  }>;
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  };
  author?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'author';
  };
  publishedAt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
    | ({
        _key: string;
      } & Table)
    | ({
        _key: string;
      } & FaqBlock)
    | {
        enabled?: boolean;
        _type: 'emailSignup';
        _key: string;
      }
  >;
  isFeatured?: boolean;
  isTrending?: boolean;
  excerpt?: string;
  tableOfContents?: {
    enabled?: boolean;
    title?: string;
  };
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type Table = {
  _type: 'table';
  rows?: Array<{
    cells?: Array<string>;
    _type: 'row';
    _key: string;
  }>;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | FaqBlock
  | Post
  | Author
  | Category
  | Table
  | BlockContent
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/queries.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[  _type == "category"] | order(publishedAt desc) {  _id,  title,  "slug": slug.current,  description,  image}
export type ALL_CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
}>;
// Variable: ALL_POSTS_QUERY
// Query: *[    _type == "post" &&    isBoostHustle != true &&    ($searchTerm == "" || (      title match $searchTerm ||      excerpt match $searchTerm ||      pt::text(body) match $searchTerm    )) &&    ($categorySlug == "" || category->slug.current == $categorySlug)  ] | order(publishedAt desc){    title,    "slug": slug.current,    publishedAt,    excerpt,    isFeatured,    body,    mainImage{      asset->{        _id,        url      },      alt    },    category->{      title,      "slug": slug.current    },    author->{      name,      image,      "slug": slug.current,      bio    },  }
export type ALL_POSTS_QUERYResult = Array<{
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  isFeatured: boolean | null;
  body: Array<
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & Table)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        enabled?: boolean;
        _type: 'emailSignup';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  > | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  category: {
    title: string | null;
    slug: string | null;
  } | null;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    slug: string | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
  } | null;
}>;
// Variable: POST_QUERY
// Query: *[_type=='post' && slug.current == $slug][0]{    _id,    _updatedAt,    title,    "slug": slug.current,    excerpt,    publishedAt,    "author": author->{      name,      "slug": slug.current,      image{        asset->{          _id,          url        },        alt      },      bio    },    "category": category->{      title,      "slug": slug.current    },    mainImage{      asset->{        url,        metadata {          dimensions        }      },      alt    },    body[]{      ...,      _type == "faqBlock" => {        _type,        title,        faqs[]{          question,          answer        }      },      _type == "image" => {        ...,        asset->      }    },    "wordCount": length(pt::text(body)),    "readingTime": round(length(pt::text(body)) / 5 / 180)}
export type POST_QUERYResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  author: {
    name: string | null;
    slug: string | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
      alt: null;
    } | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
  } | null;
  category: {
    title: string | null;
    slug: string | null;
  } | null;
  mainImage: {
    asset: {
      url: string | null;
      metadata: {
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        enabled?: boolean;
        _type: 'emailSignup';
        _key: string;
      }
    | {
        _key: string;
        _type: 'faqBlock';
        title: string | null;
        faqs: Array<{
          question: string | null;
          answer: Array<{
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: 'span';
              _key: string;
            }>;
            style?:
              | 'blockquote'
              | 'h1'
              | 'h2'
              | 'h3'
              | 'h4'
              | 'h5'
              | 'h6'
              | 'normal';
            listItem?: 'bullet' | 'number';
            markDefs?: Array<{
              href?: string;
              _type: 'link';
              _key: string;
            }>;
            level?: number;
            _type: 'block';
            _key: string;
          }> | null;
        }> | null;
      }
    | {
        asset: {
          _id: string;
          _type: 'sanity.imageAsset';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
    | {
        _key: string;
        _type: 'table';
        rows?: Array<{
          cells?: Array<string>;
          _type: 'row';
          _key: string;
        }>;
      }
  > | null;
  wordCount: number;
  readingTime: number;
} | null;
// Variable: POSTS_BY_CATEGORY
// Query: *[  _type == "post" &&   category->slug.current == $category] | order(publishedAt desc){  title,  "slug": slug.current,  publishedAt,  excerpt,  isFeatured,  body,  mainImage{    asset->{      _id,      url    },    alt  },  category->{    title,    "slug": slug.current  },  author->{      name,      image,      "slug": slug.current,      bio    },}
export type POSTS_BY_CATEGORYResult = Array<{
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  isFeatured: boolean | null;
  body: Array<
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & Table)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        enabled?: boolean;
        _type: 'emailSignup';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  > | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  category: {
    title: string | null;
    slug: string | null;
  } | null;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    slug: string | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
  } | null;
}>;
// Variable: RELATED_POSTS_QUERY
// Query: *[    _type == "post" &&    slug.current != $slug &&    category->slug.current == $categorySlug  ] | order(publishedAt desc){    title,    "slug": slug.current,    publishedAt,    excerpt,    isFeatured,    mainImage{      asset->{        _id,        url      },      alt    },    category->{      title,      "slug": slug.current    },    author->{      name,      image,      "slug": slug.current,      bio    },  }
export type RELATED_POSTS_QUERYResult = Array<{
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  excerpt: string | null;
  isFeatured: boolean | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  category: {
    title: string | null;
    slug: string | null;
  } | null;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    slug: string | null;
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
  } | null;
}>;
// Variable: GET_CATEGORIES_WITH_COUNT_QUERY
// Query: *[_type == "category"]{    title,    "slug": slug.current,    image,    "count": count(*[_type == "post" && category._ref == ^._id && defined(slug.current)])  } | order(count desc)
export type GET_CATEGORIES_WITH_COUNT_QUERYResult = Array<{
  title: string | null;
  slug: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  count: number;
}>;
// Variable: AUTHOR_WITH_POSTS_QUERY
// Query: *[_type == "author" && slug.current == $authorSlug][0]{  name,  "slug": slug.current,  bio,  image{    asset->{ _id, url },    alt  },  "posts": *[    _type == "post" &&    references(^._id)  ] | order(coalesce(publishedAt, _createdAt) desc){    title,    "slug": slug.current,    publishedAt,    excerpt,    isFeatured,    mainImage{      asset->{ _id, url },      alt    },    category->{      title,      "slug": slug.current    },    author->{      name,      image{        asset->{ _id, url },        alt      },      "slug": slug.current,      bio    }  }}
export type AUTHOR_WITH_POSTS_QUERYResult = {
  name: string | null;
  slug: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: null;
  } | null;
  posts: Array<{
    title: string | null;
    slug: string | null;
    publishedAt: string | null;
    excerpt: string | null;
    isFeatured: boolean | null;
    mainImage: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
      alt: string | null;
    } | null;
    category: {
      title: string | null;
      slug: string | null;
    } | null;
    author: {
      name: string | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
        } | null;
        alt: null;
      } | null;
      slug: string | null;
      bio: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?:
          | 'blockquote'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }> | null;
    } | null;
  }>;
} | null;
// Variable: ALL_AUTHORS_QUERY
// Query: *[  _type == "author"] | order(name asc) {  _id,  name,  "slug": slug.current,  bio,  image {    asset -> {      _id,      url    },    alt  },}
export type ALL_AUTHORS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: null;
  } | null;
}>;
// Variable: PREVIOUS_POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    "previousPost": *[_type == "post" && _updatedAt < ^._updatedAt && publishedAt <= now()]     | order(_updatedAt desc)[0] {      title,      "slug": slug.current,      publishedAt,      _updatedAt    }  }.previousPost
export type PREVIOUS_POST_QUERYResult = {
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  _updatedAt: string;
} | null;
// Variable: NEXT_POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    "nextPost": *[_type == "post" && _updatedAt > ^._updatedAt && publishedAt <= now()]     | order(_updatedAt asc)[0] {      title,      "slug": slug.current,      publishedAt,      _updatedAt    }  }.nextPost
export type NEXT_POST_QUERYResult = {
  title: string | null;
  slug: string | null;
  publishedAt: string | null;
  _updatedAt: string;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[\n  _type == "category"\n] | order(publishedAt desc) {\n  _id,\n  title,\n  "slug": slug.current,\n  description,\n  image\n}': ALL_CATEGORIES_QUERYResult;
    '\n  *[\n    _type == "post" &&\n    isBoostHustle != true &&\n    ($searchTerm == "" || (\n      title match $searchTerm ||\n      excerpt match $searchTerm ||\n      pt::text(body) match $searchTerm\n    )) &&\n    ($categorySlug == "" || category->slug.current == $categorySlug)\n  ] | order(publishedAt desc){\n    title,\n    "slug": slug.current,\n    publishedAt,\n    excerpt,\n    isFeatured,\n    body,\n    mainImage{\n      asset->{\n        _id,\n        url\n      },\n      alt\n    },\n    category->{\n      title,\n      "slug": slug.current\n    },\n    author->{\n      name,\n      image,\n      "slug": slug.current,\n      bio\n    },\n  }\n': ALL_POSTS_QUERYResult;
    '*[_type==\'post\' && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    "author": author->{\n      name,\n      "slug": slug.current,\n      image{\n        asset->{\n          _id,\n          url\n        },\n        alt\n      },\n      bio\n    },\n    "category": category->{\n      title,\n      "slug": slug.current\n    },\n    mainImage{\n      asset->{\n        url,\n        metadata {\n          dimensions\n        }\n      },\n      alt\n    },\n    body[]{\n      ...,\n      _type == "faqBlock" => {\n        _type,\n        title,\n        faqs[]{\n          question,\n          answer\n        }\n      },\n      _type == "image" => {\n        ...,\n        asset->\n      }\n    },\n    "wordCount": length(pt::text(body)),\n    "readingTime": round(length(pt::text(body)) / 5 / 180)\n}': POST_QUERYResult;
    '*[\n  _type == "post" && \n  category->slug.current == $category\n] | order(publishedAt desc){\n  title,\n  "slug": slug.current,\n  publishedAt,\n  excerpt,\n  isFeatured,\n  body,\n  mainImage{\n    asset->{\n      _id,\n      url\n    },\n    alt\n  },\n  category->{\n    title,\n    "slug": slug.current\n  },\n  author->{\n      name,\n      image,\n      "slug": slug.current,\n      bio\n    },\n}': POSTS_BY_CATEGORYResult;
    '\n  *[\n    _type == "post" &&\n    slug.current != $slug &&\n    category->slug.current == $categorySlug\n  ] | order(publishedAt desc){\n    title,\n    "slug": slug.current,\n    publishedAt,\n    excerpt,\n    isFeatured,\n    mainImage{\n      asset->{\n        _id,\n        url\n      },\n      alt\n    },\n    category->{\n      title,\n      "slug": slug.current\n    },\n    author->{\n      name,\n      image,\n      "slug": slug.current,\n      bio\n    },\n  }\n': RELATED_POSTS_QUERYResult;
    '\n  *[_type == "category"]{\n    title,\n    "slug": slug.current,\n    image,\n    "count": count(*[_type == "post" && category._ref == ^._id && defined(slug.current)])\n  } | order(count desc)\n': GET_CATEGORIES_WITH_COUNT_QUERYResult;
    '\n*[_type == "author" && slug.current == $authorSlug][0]{\n  name,\n  "slug": slug.current,\n  bio,\n  image{\n    asset->{ _id, url },\n    alt\n  },\n  "posts": *[\n    _type == "post" &&\n    references(^._id)\n  ] | order(coalesce(publishedAt, _createdAt) desc){\n    title,\n    "slug": slug.current,\n    publishedAt,\n    excerpt,\n    isFeatured,\n    mainImage{\n      asset->{ _id, url },\n      alt\n    },\n    category->{\n      title,\n      "slug": slug.current\n    },\n    author->{\n      name,\n      image{\n        asset->{ _id, url },\n        alt\n      },\n      "slug": slug.current,\n      bio\n    }\n  }\n}\n': AUTHOR_WITH_POSTS_QUERYResult;
    '*[\n  _type == "author"\n] | order(name asc) {\n  _id,\n  name,\n  "slug": slug.current,\n  bio,\n  image {\n    asset -> {\n      _id,\n      url\n    },\n    alt\n  },\n}': ALL_AUTHORS_QUERYResult;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    "previousPost": *[_type == "post" && _updatedAt < ^._updatedAt && publishedAt <= now()] \n    | order(_updatedAt desc)[0] {\n      title,\n      "slug": slug.current,\n      publishedAt,\n      _updatedAt\n    }\n  }.previousPost\n': PREVIOUS_POST_QUERYResult;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    "nextPost": *[_type == "post" && _updatedAt > ^._updatedAt && publishedAt <= now()] \n    | order(_updatedAt asc)[0] {\n      title,\n      "slug": slug.current,\n      publishedAt,\n      _updatedAt\n    }\n  }.nextPost\n': NEXT_POST_QUERYResult;
  }
}
