import Footer from "@/components/layout/footer";
import NavBar from "@/components/layout/navbar";
import type { Metadata } from "next";
import { Manrope, Marcellus } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider } from "next-themes";

/* Barlow */
/* Manrope */

const outfit = Manrope({
	weight: ["300", "400", "500", "600", "700"],
	variable: "--font-outfit",
	subsets: ["latin"],
});

const marcellus = Marcellus({
	weight: "400",
	variable: "--font-marcellus",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${outfit.className} ${marcellus.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<NavBar />
					{children}
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	);
}
