import Footer from "@/components/layout/footer";
import NavBar from "@/components/layout/navbar";
import type { Metadata } from "next";
import { Marcellus, Outfit } from "next/font/google";
import "../styles/globals.css";

const outfit = Outfit({
	variable: "--font-outfit",
	subsets: ["latin"],
});

const marcellus = Marcellus({
	weight: "400",
	variable: "--font-marcellus",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${outfit.className} ${marcellus.variable} antialiased`}>
				<NavBar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
